import 'dart:io';
import 'dart:async';
import 'dart:convert';

// To generate unicode.dart you should download http://www.unicode.org/Public/6.3.0/ucd/UnicodeData.txt

String toCondition(List<int> codes) {
  // TODO Overall condition optimization (too many data!!!)
  // TODO add support to interspace like (c >= a && c <= b && c & 1 == 0)
  List<String> result = <String>[];
  bool inRange = false;
  int rangeStart;
  for (int i = 0; i < codes.length - 1; ++i) {
    if (codes[i] + 1 == codes[i + 1]) {
      if (!inRange) {
        inRange = true;
        rangeStart = codes[i];
      }
    } else {
      if (inRange) {
        inRange = false;
        result.add('(c>=${rangeStart}&&c<=${codes[i]})');
      } else {
        result.add('c==${codes[i]}');
      }
    }
  }
  if (inRange) {
    result.add('(c>=${rangeStart} && c<=${codes.last})');
  } else {
    result.add('c==${codes.last}');
  }

  if (result.length == 0) {
    return 'false';
  } else {
    return result.join('||');
  }
}

void processFile(List<String> lines) {
  List<int> spaces = <int>[];
  List<int> lower = <int>[];
  List<int> upper = <int>[];
  List<int> alpha = <int>[];
  List<int> alphaNum = <int>[];

  lines.forEach((String line) {
    List<String> data = line.split(';');
    int code = int.parse(data[0], radix: 16);
    String cls = data[2];
    switch (cls) {
    case 'Zs':
      spaces.add(code);
      break;

    case 'Ll':
      lower.add(code);
      alpha.add(code);
      alphaNum.add(code);
      break;

    case 'Lu':
    case 'Lt':
      upper.add(code);
      alpha.add(code);
      alphaNum.add(code);
      break;

    case 'Lm':
    case 'Lo':
      alpha.add(code);
      alphaNum.add(code);
      break;

    case 'Mc':
    case 'Me':
    case 'Mn':
    case 'Nd':
    case 'Nl':
    case 'No':
      alphaNum.add(code);
      break;
    }
  });

  var file = new File('lib/src/unicode.dart');
  // TODO wrap lines;
  IOSink sink = file.openWrite();
  sink.writeln("// This file is autogenerated. Do not edit.");
  sink.writeln();
  sink.writeln('part of parsec;');
  sink.writeln();


  sink.write(r"bool isSpace(int c) => c==9||c==10||c==11||c==13||");
  sink.write(toCondition(spaces));
  sink.writeln(';');

  sink.write(r"bool isLower(int c) => ");
  sink.write(toCondition(lower));
  sink.writeln(';');

  sink.write(r"bool isUpper(int c) => ");
  sink.write(toCondition(upper));
  sink.writeln(';');

  sink.write(r"bool isAlpha(int c) => ");
  sink.write(toCondition(alpha));
  sink.writeln(';');

  sink.write(r"bool isAlphaNum(int c) => ");
  sink.write(toCondition(alphaNum));
  sink.writeln(';');

}

void main() {
  var file = new File('UnicodeData.txt');
  Future<List<String>> finishedReading = file.readAsLines(encoding: ASCII);
  finishedReading.then(processFile);
}
